var storyJSON = 
{

	"paragraphs":
	[
		"Thunder cackles and lightning strikes with a brilliant flash across the dark sky. Three witches materialize out of the night in a forest far from civilization, accompanied as always by their familiars. Each acknowledges the others with a nod and with one voice they chant an ancient prophecy:",
		"BLOCKQUOTE:From hay and dust a poor woman born,<br />Bound by birth to the silver plate.<br />When chains are broken and fortunes turn,<br />A man of sword will meet his fate.<br />Kings will rise and kings will fall,<br />As violence brews in Scotland's halls,<br />And back to dust will woman return.",
		"CENTER:&#8226;  &#8226;  &#8226;",
		"I always knew I wanted to be queen. Since I was a girl, I have dreamed of the power and luxury enjoyed by the royal family. Some have called me overambitious or even crazy for believing I could ever be a queen, yet here I am today – Lady Macbeth, Queen of Scotland. But, it wasn't always this way. In fact, I wasn't even born into nobility. No, my dreams and I come from far humbler origins.",
		"My parents were not nobles or royals but rather a pair of common peasants. They owned a small farm in the outskirts of Perth on land rented from Lord MacElliott. My parents died of plague when I was only five, and I moved into Lord MacElliott's castle as a servant. For the next few years, I worked aside the other women servants cooking and cleaning for the MacElliott family. Occasionally I would also attend to Lord MacElliott's daughter Allie. Allie and I were about the same age so we got along well with one another. Back then I was still na&#239;ve enough to believe two girls from different social classes could become friends. I was too young to realize any difference between nobles and peasants and foolishly believed that a servant could be treated as an equal to a lady. That all changed the day I met the witches.",
		"It was a cold December morning, a dark day even for winter. Allie sent me out to the forest a few miles north of the castle to collect firewood. Suddenly, as I was picking up a long stick, three old hags appeared in the forest around me. \"All hail Lady Macbeth!\" the first one cried out in greeting. \"Hail to thee, Lady of Glamis and Queen of Scotland!\"",
		"\"Lady, who?\" I responded. \"I have never heard that name before. You must have mistaken me for someone else. I am but a humble servant of Lord MacElliott.\"",
		"\"You were born poor yes, but you are destined for so much more,\" answered the second witch.",
		"\"Destiny? What do you mean?\"",
		"\"Haven't you noticed the lives of luxury that the MacElliotts live while you, a servant, are forced to work day and night? That they treat you differently from one another, as though you are an inferior being? It does not have to be this way. Your future holds all they have and more if you follow the right path.\"",
		"\"I don't understand! Please, I beg of you, tell me more.\"",
		"\"Farewell, Lady Macbeth.\" replied the third witch. \"Never forget that fate will always guide you.\" And with a snap of their fingers, the three witches vanished, leaving no sign that they had ever been in the forest.",
		"The witches' cryptic visit troubled me for days to the point that I began to question if they had been real in the first place. However, I also began to notice more and more ways that the MacElliotts were different from me and acted as though they were better than everyone else in the castle. Real or not, the witches opened my eyes to reality: the MacElliotts and I belonged to different social classes and I could never hope to amount to anything without a \"Lord\" or \"Lady\" in front of my name. Over time, I harbored a great jealousy of Allie's life and desired by any means possible to induct myself into the nobility.",
		"My opportunity presented itself exactly two years after my meeting with the witches. Lord MacElliott announced that Allie was to be married to a man by the name of Macbeth in order to cement an alliance between Perth and neighboring Inverness. He declared that there would be a celebration at home then Allie would be sent off alone for a small ceremony at Inverness castle. After hearing the name Macbeth, I knew that this was the chance that the witches spoke of in the forest. Fate itself decreed that I must take Allie's place and become Lady Macbeth in her stead. In the weeks that followed Lord MacElliott's announcement, I plotted out my plan to swap places with Allie and then waited patiently for the wedding.",
		"The day Allie departed for Inverness, I followed closely behind out of the castle. Although her escort was small, they moved slowly enough that I could easily keep up on foot. On the first night as they stopped for a rest, I snuck into their camp and hid until I was confident Allie had been left alone by her guards. I quietly crept towards Allie's back from my hiding place and, before she could make a noise, swiftly slit her throat with I blade I had stolen from the castle. Careful not to alert the guards, I dragged Allie's limp body to a secluded location and changed into her clothes after cleaning any blood that soaked into them. Luckily I looked similar enough to Allie that nobody asked any questions and the rest of the trip passed uneventfully.",
		"I married Macbeth as anticipated without raising any suspicions since he had never met Allie before. Adjusting to the life of a noblewoman was much easier than I expected but just as amazing as I had dreamed. Macbeth was young back then and he rose very quickly up the ranks of nobility through his military prowess and good fortune over the next few years. Even King Duncan recognized Macbeth's skill with a sword and named him a captain in the war against the rebel Thane of Cawdor. It was during this very war that Macbeth met the same three witches who had once visited me and subsequently received the thaneships of Glamis and Cawdor from Duncan.",
		"Shortly before returning home from the war, Macbeth wrote to me about his encounter with the witches and their prediction of his ascension to king. When he added that Duncan would be visiting our castle soon I knew that fate had sent me another opportunity. I immediately began planning for my second assassination and presented my ideas to Macbeth when he came home. At first he was reluctant to commit what he saw as an act of treason, but I soon convinced him to see my way. Duncan arrived at Inverness shortly after and left the next day in a coffin. Both plan and king were executed perfectly without any evidence pointing our way.",
		"However, despite our initial triumph success was ultimately short lived. Not long after Macbeth's crowning as king, Banquo started to act suspicious of us and we had to take care of him. Unfortunately, his death made an enemy of Macduff, who fled Scotland seeking help from the English king. And, to make matters worse, my foolish husband began seeing ghosts and raving like a madman to empty chairs! I fear that he actually feels guilty for killing Duncan and Banquo as if he were a weak child. I'll admit that I have experienced nightmares of my own since the assassination, but they are from paranoia, not guilt! Duncan's death was completely justified by fate, so why would I be guilty. I was merely worried about Macduff since it had been rumored he was gathering an army down in England.",
		"As it would turn out, my paranoia was well founded. Just this morning, Macduff arrived at our castle with an English army at his heels. Macbeth believes that they cannot kill him because of a new prophecy that the witches gave him. They declared that he would only die the day Birnam Wood moved to Dunsinane and at the hand of man not born of woman. Today I have seen Birnam Wood march on Dunsinane, albeit symbolically by Macduff's army carrying trees cut from the woods. I do not know how there could be such a thing as a man not born of woman, but I do know that the witches have never been wrong in their predictions before. It is clear that fate has turned its back on us and sided with Macduff in this coming battle. Therefore, I have decided to end my own life. I would rather die at my own hand then cowardly wait for Macduff to do the deed for me. I pull out a silver blade, plunge it towards my chest, and then darkness."
	]

}